openapi: 3.0.1
info:
  title: Wheel Alignment API
  description: API for the Wheel Alignment iOS App
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
security:
  - cognitoAuth: []
paths:
  /alignments:
    post:
      summary: Start a new alignment session
      security:
        - cognitoAuth: []
      requestBody:
        description: Alignment object to create a new session
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Alignment'
      responses:
        '201':
          description: Alignment session started successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alignment'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
    get:
      summary: List all alignments for a user
      security:
        - cognitoAuth: []
      parameters:
        - name: technicianId
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: List of alignments retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Alignment'
        '401':
          description: Unauthorized

components:
  schemas:
    Alignment:
      type: object
      properties:
        alignmentId:
          type: string
        vehicleVin:
          type: string
        technicianId:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        status:
          type: string
          enum:
            - in-progress
            - completed
      required:
        - alignmentId
        - vehicleVin
        - technicianId
        - startTime
        - status